name: Test

on:
  repository_dispatch:
    types: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:

      - name: Prompt branch name
        shell: bash
        run: echo "HERE"


      - name: Prompt branch name
        shell: bash
        run: echo "${{ github.event.client_payload.key }}"
